// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package keyvalue

import (
	"context"
	"fmt"

	"github.com/michilu/boilerplate/service/errs"
	"github.com/michilu/boilerplate/service/slog"
	"github.com/rs/zerolog"
	"go.opencensus.io/trace"
	"google.golang.org/grpc/codes"
)

// KeyValueWithContext is KeyValue with context.Context.
type KeyValueWithContext struct {
	Context  context.Context
	KeyValue KeyValuer
}

// GetContext returns context.Context.
func (p *KeyValueWithContext) GetContext() context.Context {
	return p.Context
}

// GetKeyValue returns KeyValuer.
func (p *KeyValueWithContext) GetKeyValue() KeyValuer {
	return p.KeyValue
}

// MarshalZerologObject writes KeyValueWithContext to given zerolog.Event.
func (p *KeyValueWithContext) MarshalZerologObject(e *zerolog.Event) {
	if p.KeyValue == nil {
		return
	}
	v0, ok := p.KeyValue.(zerolog.LogObjectMarshaler)
	if !ok {
		const op = op + ".KeyValueWithContext.MarshalZerologObject.type-assetion"
		err := &errs.Error{Op: op, Code: codes.InvalidArgument,
			Message: "'*KeyValueWithContext.KeyValue' must be zerolog.LogObjectMarshaler'"}
		v1 := slog.Logger().Err(err).Str("op", op)
		if p.Context != nil {
			ctx, s := trace.StartSpan(p.Context, op)
			defer s.End()
			v1.EmbedObject(slog.Atrace(ctx))
		}
		v1.Msg(err.Error())
		return
	}
	e.Object(op+".KeyValueWithContext", v0)
}

// String returns KeyValueWithContext as string.
func (p *KeyValueWithContext) String() string {
	const v0 = op + ".KeyValueWithContext<Context: %v, KeyValue: %v>"
	if p.KeyValue == nil {
		return fmt.Sprintf(v0, p.Context, p.KeyValue)
	}
	v1, ok := p.KeyValue.(fmt.Stringer)
	if !ok {
		return fmt.Sprintf(v0, p.Context, p.KeyValue)
	}
	return fmt.Sprintf(v0, p.Context, v1.String())
}

// Validate returns error if failed validate.
func (p *KeyValueWithContext) Validate() error {
	const op = op + ".KeyValueWithContext.Validate"
	if p.Context == nil {
		err := &errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. '*KeyValueWithContext.Context' is nil"}
		return err
	}
	if p.KeyValue == nil {
		err := &errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. '*KeyValueWithContext.KeyValue' is nil"}
		return err
	}
	v0, ok := p.KeyValue.(interface{ Validate() error })
	if !ok {
		err := &errs.Error{Op: op, Code: codes.InvalidArgument, Message: "'*KeyValueWithContext.KeyValue' must be have 'Validate() error'"}
		return err
	}
	{
		err := v0.Validate()
		if err != nil {
			err := &errs.Error{Op: op, Code: codes.InvalidArgument, Err: err}
			return err
		}
	}
	return nil
}
