// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package keyvalue

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Key) Validate() error {
	if !(len(this.Key) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Key", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Key))
	}
	return nil
}
func (this *KeyValue) Validate() error {
	if !(len(this.Key) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Key", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Key))
	}
	if !(len(this.Value) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Value", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Value))
	}
	return nil
}
func (this *Prefix) Validate() error {
	if !(len(this.Prefix) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Prefix", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Prefix))
	}
	return nil
}
