@startuml

package "event" {
	interface "EventLoggerGetContexter" as event.EventLoggerGetContexter {
		+GetContext(): context.Context
	}
}



package "event" {
	class "Saver" as event.Saver <<V,Orchid>> {
		+Saver: event.Saver
		+Save(m: keyvalue.KeyValueWithContexter): (context.Context, error)
	}
}

	event.Saver --> event.Saver


package "event" {
	interface "SaverGetContexter" as event.SaverGetContexter {
		+GetContext(): context.Context
	}
}



package "event" {
	interface "StartGetContexter" as event.StartGetContexter {
		+GetContext(): context.Context
	}
}



package "event" {
	class "topic" as event.topic <<V,Orchid>>
}



package "exporter" {
	class "GlobalMonitoredResource" as exporter.GlobalMonitoredResource <<V,Orchid>> {
		-projectID: string
		+MonitoredResource(): (string, map[string]string)
	}
}



package "run" {
	class "topic" as run.topic <<V,Orchid>>
}



package "update" {
	class "topic" as update.topic <<V,Orchid>>
}



	event.EventLoggerGetContexter -up-|> event.SaverGetContexter
	event.EventLoggerGetContexter -up-|> event.StartGetContexter
	event.SaverGetContexter -up-|> event.EventLoggerGetContexter
	event.SaverGetContexter -up-|> event.StartGetContexter
	event.StartGetContexter -up-|> event.EventLoggerGetContexter
	event.StartGetContexter -up-|> event.SaverGetContexter


@enduml
