@startuml

package "run" {
	class "topic" as run.topic <<V,Orchid>>
}



package "update" {
	class "topic" as update.topic <<V,Orchid>>
}



package "debug" {
	class "Config" as debug.Config <<V,Orchid>> {
		-ctx: context.Context
		-clientRepo: debug.ClientRepository
		+Config(ctx: context.Context): (debug.ClientWithContexter, error)
		+Connect(m: debug.ClientWithContexter): (context.Context, error)
	}
}



package "debug" {
	interface "ConfigGetContexter" as debug.ConfigGetContexter {
		+GetContext(): context.Context
	}
}



package "debug" {
	interface "Configer" as debug.Configer {
		+Config(: context.Context): (debug.ClientWithContexter, error)
		+Connect(: debug.ClientWithContexter): (context.Context, error)
	}
}



package "debug" {
	interface "ConnectGetContexter" as debug.ConnectGetContexter {
		+GetContext(): context.Context
	}
}



package "debug" {
	class "clientRepository" as debug.clientRepository <<E,#FFCC00>> {
		+Config(ctx: context.Context): (debug.ClientWithContexter, error)
		+Connect(m: debug.ClientWithContexter): error
	}
}



package "debug" {
	class "topic" as debug.topic <<V,Orchid>>
}



package "event" {
	interface "EventLoggerGetContexter" as event.EventLoggerGetContexter {
		+GetContext(): context.Context
	}
}



package "event" {
	class "Saver" as event.Saver <<V,Orchid>> {
		+Saver: event.Saver
		+Save(m: event.KeyValueWithContexter): (context.Context, error)
	}
}

	event.Saver --> event.Saver


package "event" {
	interface "SaverGetContexter" as event.SaverGetContexter {
		+GetContext(): context.Context
	}
}



package "event" {
	interface "StartGetContexter" as event.StartGetContexter {
		+GetContext(): context.Context
	}
}



package "event" {
	interface "TopicEventEventWithContexter" as event.TopicEventEventWithContexter {
		+Publish(ctx: context.Context, c: event.EventWithContexter)
		+Publisher(ctx: context.Context): event.EventWithContexter
		+Subscribe(c: event.EventWithContexter)
	}
}



package "event" {
	interface "TopicEventKeyValueWithContexter" as event.TopicEventKeyValueWithContexter {
		+Publish(ctx: context.Context, c: event.KeyValueWithContexter)
		+Publisher(ctx: context.Context): event.KeyValueWithContexter
		+Subscribe(c: event.KeyValueWithContexter)
	}
}



package "event" {
	class "mapEventEventWithContexter" as event.mapEventEventWithContexter <<V,Orchid>> {
		-mu: sync.RWMutex
		-m: map[interface{}]*event.tEventEventWithContexter
		-get(topic: interface{}): event.TopicEventEventWithContexter
	}
}



package "event" {
	class "mapEventKeyValueWithContexter" as event.mapEventKeyValueWithContexter <<V,Orchid>> {
		-mu: sync.RWMutex
		-m: map[interface{}]*event.tEventKeyValueWithContexter
		-get(topic: interface{}): event.TopicEventKeyValueWithContexter
	}
}



package "event" {
	class "tEventEventWithContexter" as event.tEventEventWithContexter <<E,#FFCC00>> {
		-mu: sync.RWMutex
		-c: event.EventWithContexter
		+Publish(ctx: context.Context, c: event.EventWithContexter)
		+Publisher(ctx: context.Context): event.EventWithContexter
		+Subscribe(c: event.EventWithContexter)
	}
}



package "event" {
	class "tEventKeyValueWithContexter" as event.tEventKeyValueWithContexter <<E,#FFCC00>> {
		-mu: sync.RWMutex
		-c: event.KeyValueWithContexter
		+Publish(ctx: context.Context, c: event.KeyValueWithContexter)
		+Publisher(ctx: context.Context): event.KeyValueWithContexter
		+Subscribe(c: event.KeyValueWithContexter)
	}
}



package "event" {
	class "topic" as event.topic <<V,Orchid>>
}



package "exporter" {
	class "GlobalMonitoredResource" as exporter.GlobalMonitoredResource <<V,Orchid>> {
		-projectID: string
		+MonitoredResource(): (string, map[string]string)
	}
}



	debug.Config -up-|> debug.Configer
	debug.ConfigGetContexter -up-|> debug.ConnectGetContexter
	debug.ConfigGetContexter -up-|> event.EventLoggerGetContexter
	debug.ConfigGetContexter -up-|> event.SaverGetContexter
	debug.ConfigGetContexter -up-|> event.StartGetContexter
	debug.ConnectGetContexter -up-|> debug.ConfigGetContexter
	debug.ConnectGetContexter -up-|> event.EventLoggerGetContexter
	debug.ConnectGetContexter -up-|> event.SaverGetContexter
	debug.ConnectGetContexter -up-|> event.StartGetContexter
	event.EventLoggerGetContexter -up-|> debug.ConfigGetContexter
	event.EventLoggerGetContexter -up-|> debug.ConnectGetContexter
	event.EventLoggerGetContexter -up-|> event.SaverGetContexter
	event.EventLoggerGetContexter -up-|> event.StartGetContexter
	event.SaverGetContexter -up-|> debug.ConfigGetContexter
	event.SaverGetContexter -up-|> debug.ConnectGetContexter
	event.SaverGetContexter -up-|> event.EventLoggerGetContexter
	event.SaverGetContexter -up-|> event.StartGetContexter
	event.StartGetContexter -up-|> debug.ConfigGetContexter
	event.StartGetContexter -up-|> debug.ConnectGetContexter
	event.StartGetContexter -up-|> event.EventLoggerGetContexter
	event.StartGetContexter -up-|> event.SaverGetContexter
	event.tEventEventWithContexter -up-|> event.TopicEventEventWithContexter
	event.tEventKeyValueWithContexter -up-|> event.TopicEventKeyValueWithContexter


@enduml
