@startuml

queue update..time.Time[
topic("update")
--
time.Time
]

queue update..Durationer[
topic("update")
--
Durationer
]

actor ticker.C
ticker.C->update..time.Time
cmd.update->update..time.Time
update..time.Time->update
update->update..Durationer
update..Durationer->restart
restart.>update..Durationer

@enduml