[gcp.logging]
id=''
[application.debug.client]
id=''
[application.debug.open-debug-port]
command='ssh -i ~/.ssh/id_ed25519 -R 12345:localhost:12345 user@localhost while true;do sleep 1d;done'
[aws.iot]
arn=''
