[google.application]
credentials=''
[gcp.project]
id=''
[gcp.logging]
id=''
[service.profile.pprof]
addr=':8888'
[service.profile.profiler]
debug-logging=true
[service.update]
channel='release'
url='https://michilu.github.io/boilerplate/'
[application.debug.client]
id=''
[application.debug.open-debug-port]
command='ssh -i ~/.ssh/id_ed25519 -R 12345:localhost:12345 user@localhost while true;do sleep 1d;done'
[application.event]
enable=true
[infra.nutsdb.event]
path='assets/db/event.db'
