@startuml

queue system..event[
topic("system")
--
context.Context
Event
]

queue event..byte[
topic("event")
--
context.Context
[]byte
]

actor system
system->system..event
system..event->:event logger:
:event logger:->event..byte
event..byte->saver

@enduml
