// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package event

import (
	"context"

	"github.com/michilu/boilerplate/service/errs"
	"google.golang.org/grpc/codes"
)

type EventLoggerGetContexter interface {
	GetContext() context.Context
}

// GetPipeEventLogger returns new input(chan<- EventWithContexter)/output(<-chan KeyValueWithContexter) channels that embedded the given 'func(EventWithContexter) KeyValueWithContexter'.
func GetPipeEventLogger(
	ctx context.Context,
	fn func(EventWithContexter) (KeyValueWithContexter, error),
	fnErr func(context.Context, error) bool,
) (
	chan<- EventWithContexter,
	<-chan KeyValueWithContexter,
) {
	const op = op + ".GetPipeEventLogger"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if fn == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fn' is nil"})
	}
	if fnErr == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fnErr' is nil"})
	}

	inCh := make(chan EventWithContexter)
	outCh := make(chan KeyValueWithContexter)

	go func() {
		const op = op + "#go"
		defer close(outCh)
		for i := range inCh {
			o, err := fn(i)
			if err != nil {
				var vctx context.Context
				vctx, ok := i.(context.Context)
				if !ok {
					v, ok := i.(EventLoggerGetContexter)
					if ok {
						vctx = v.GetContext()
					} else {
						vctx = context.Background()
					}
				}
				if fnErr(vctx, &errs.Error{Op: op, Err: err}) {
					return
				}
				continue
			}
			select {
			case <-ctx.Done():
				err := ctx.Err()
				if err != nil {
					fnErr(ctx, &errs.Error{Op: op, Err: err})
				}
				return
			case outCh <- o:
			default:
			}
		}
	}()

	return inCh, outCh
}

// GetFanoutEventLogger returns new input(chan<- EventWithContexter)/output(<-chan KeyValueWithContexter) channels that embedded the given 'func(EventWithContexter) KeyValueWithContexter'.
func GetFanoutEventLogger(
	ctx context.Context,
	fn func(EventWithContexter) ([]KeyValueWithContexter, error),
	fnErr func(context.Context, error) bool,
) (
	chan<- EventWithContexter,
	<-chan KeyValueWithContexter,
) {
	const op = op + ".GetFanoutEventLogger"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if fn == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fn' is nil"})
	}
	if fnErr == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fnErr' is nil"})
	}

	inCh := make(chan EventWithContexter)
	outCh := make(chan KeyValueWithContexter)

	go func() {
		const op = op + "#go"
		defer close(outCh)
		for i := range inCh {
			o, err := fn(i)
			if err != nil {
				var vctx context.Context
				vctx, ok := i.(context.Context)
				if !ok {
					v, ok := i.(EventLoggerGetContexter)
					if ok {
						vctx = v.GetContext()
					} else {
						vctx = context.Background()
					}
				}
				if fnErr(vctx, &errs.Error{Op: op, Err: err}) {
					return
				}
				continue
			}
			for _, v := range o {
				select {
				case <-ctx.Done():
					err := ctx.Err()
					if err != nil {
						fnErr(ctx, &errs.Error{Op: op, Err: err})
					}
					return
				case outCh <- v:
				default:
				}
			}
		}
	}()

	return inCh, outCh
}
