// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package event

import (
	"context"

	"github.com/michilu/boilerplate/service/errs"
	"github.com/michilu/boilerplate/service/event"
	"go.opencensus.io/trace"
	"google.golang.org/grpc/codes"
)

type StartGetContexter interface {
	GetContext() context.Context
}

// GetPipeStart returns new input(chan<- ContextContext)/output(<-chan EventEventWithContexter) channels that embedded the given 'func(ContextContext) EventEventWithContexter'.
func GetPipeStart(
	ctx context.Context,
	fn func(context.Context) (event.EventWithContexter, error),
	fnErr func(context.Context, error) bool,
) (
	chan<- context.Context,
	<-chan event.EventWithContexter,
) {
	const op = op + ".GetPipeStart"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if fn == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fn' is nil"})
	}
	if fnErr == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fnErr' is nil"})
	}

	inCh := make(chan context.Context)
	outCh := make(chan event.EventWithContexter)

	go func() {
		const op = op + "#go"
		defer close(outCh)
		for i := range inCh {
			o, err := fn(i)
			if err != nil {
				var vctx context.Context
				vctx, ok := i.(context.Context)
				if !ok {
					v, ok := i.(StartGetContexter)
					if ok {
						vctx = v.GetContext()
					} else {
						vctx = context.Background()
					}
				}
				if fnErr(vctx, &errs.Error{Op: op, Err: err}) {
					return
				}
				continue
			}
			select {
			case <-ctx.Done():
				err := ctx.Err()
				if err != nil {
					fnErr(ctx, &errs.Error{Op: op, Err: err})
				}
				return
			case outCh <- o:
			}
		}
	}()

	return inCh, outCh
}

// GetFanoutStart returns new input(chan<- ContextContext)/output(<-chan EventEventWithContexter) channels that embedded the given 'func(ContextContext) EventEventWithContexter'.
func GetFanoutStart(
	ctx context.Context,
	fn func(context.Context) ([]event.EventWithContexter, error),
	fnErr func(context.Context, error) bool,
) (
	chan<- context.Context,
	<-chan event.EventWithContexter,
) {
	const op = op + ".GetFanoutStart"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if fn == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fn' is nil"})
	}
	if fnErr == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fnErr' is nil"})
	}

	inCh := make(chan context.Context)
	outCh := make(chan event.EventWithContexter)

	go func() {
		const op = op + "#go"
		defer close(outCh)
		for i := range inCh {
			v0, err := fn(i)
			if err != nil {
				var ctx0 context.Context
				ctx0, ok := i.(context.Context)
				if !ok {
					v1, ok := i.(StartGetContexter)
					if ok {
						ctx0 = v1.GetContext()
					} else {
						ctx0 = context.Background()
					}
				}
				v2 := fnErr(ctx0, &errs.Error{Op: op, Err: err})
				v0 := trace.FromContext(ctx0)
				if v0 != nil {
					v0.End()
				}
				if v2 {
					return
				}
				continue
			}
			for _, v3 := range v0 {
				select {
				case <-ctx.Done():
					err := ctx.Err()
					if err != nil {
						fnErr(ctx, &errs.Error{Op: op, Err: err})
					}
					return
				case outCh <- v3:
				}
			}
		}
	}()

	return inCh, outCh
}
