// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package event

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Byte) Validate() error {
	if !(len(this.Byte) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Byte", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Byte))
	}
	return nil
}
