// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/meta/message.proto

package meta

import (
	fmt "fmt"
	math "math"
	"time"

	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Meta is ValueObject of meta infomation
type Meta struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Semver               string    `protobuf:"bytes,2,opt,name=semver,proto3" json:"semver,omitempty"`
	Channel              string    `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Runtime              *Runtime  `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Serial               string    `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	Build                time.Time `protobuf:"bytes,6,opt,name=build,proto3" json:"build,omitempty"`
	Vcs                  *Vcs      `protobuf:"bytes,7,opt,name=vcs,proto3" json:"vcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" yaml:"-"`
	XXX_unrecognized     []byte    `json:"-" yaml:"-"`
	XXX_sizecache        int32     `json:"-" yaml:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_130516f5d91467ae, []int{0}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meta) GetSemver() string {
	if m != nil {
		return m.Semver
	}
	return ""
}

func (m *Meta) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Meta) GetRuntime() *Runtime {
	if m != nil {
		return m.Runtime
	}
	return nil
}

func (m *Meta) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Meta) GetBuild() time.Time {
	return m.Build
}

func (m *Meta) GetVcs() *Vcs {
	if m != nil {
		return m.Vcs
	}
	return nil
}

// Runtime is ValueObject of Runtime
type Runtime struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Arch                 string   `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Os                   string   `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-"`
}

func (m *Runtime) Reset()         { *m = Runtime{} }
func (m *Runtime) String() string { return proto.CompactTextString(m) }
func (*Runtime) ProtoMessage()    {}
func (*Runtime) Descriptor() ([]byte, []int) {
	return fileDescriptor_130516f5d91467ae, []int{1}
}

func (m *Runtime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Runtime.Unmarshal(m, b)
}
func (m *Runtime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Runtime.Marshal(b, m, deterministic)
}
func (m *Runtime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Runtime.Merge(m, src)
}
func (m *Runtime) XXX_Size() int {
	return xxx_messageInfo_Runtime.Size(m)
}
func (m *Runtime) XXX_DiscardUnknown() {
	xxx_messageInfo_Runtime.DiscardUnknown(m)
}

var xxx_messageInfo_Runtime proto.InternalMessageInfo

func (m *Runtime) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Runtime) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *Runtime) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

// Vcs is ValueObject of VCS
type Vcs struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Branch               string   `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" yaml:"-"`
	XXX_unrecognized     []byte   `json:"-" yaml:"-"`
	XXX_sizecache        int32    `json:"-" yaml:"-"`
}

func (m *Vcs) Reset()         { *m = Vcs{} }
func (m *Vcs) String() string { return proto.CompactTextString(m) }
func (*Vcs) ProtoMessage()    {}
func (*Vcs) Descriptor() ([]byte, []int) {
	return fileDescriptor_130516f5d91467ae, []int{2}
}

func (m *Vcs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vcs.Unmarshal(m, b)
}
func (m *Vcs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vcs.Marshal(b, m, deterministic)
}
func (m *Vcs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vcs.Merge(m, src)
}
func (m *Vcs) XXX_Size() int {
	return xxx_messageInfo_Vcs.Size(m)
}
func (m *Vcs) XXX_DiscardUnknown() {
	xxx_messageInfo_Vcs.DiscardUnknown(m)
}

var xxx_messageInfo_Vcs proto.InternalMessageInfo

func (m *Vcs) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Vcs) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Vcs) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func init() {
	proto.RegisterType((*Meta)(nil), "michilu.boilerplate.service.meta.Meta")
	proto.RegisterType((*Runtime)(nil), "michilu.boilerplate.service.meta.Runtime")
	proto.RegisterType((*Vcs)(nil), "michilu.boilerplate.service.meta.Vcs")
}

func init() { proto.RegisterFile("service/meta/message.proto", fileDescriptor_130516f5d91467ae) }

var fileDescriptor_130516f5d91467ae = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6b, 0xe3, 0x30,
	0x10, 0xc5, 0x1f, 0xb1, 0x59, 0xed, 0x1e, 0x16, 0x51, 0x82, 0xc9, 0xa1, 0x35, 0xa1, 0x85, 0xf4,
	0x10, 0x1b, 0x5a, 0x68, 0x2f, 0x3d, 0xa5, 0xc7, 0x12, 0x08, 0x3a, 0x84, 0xd2, 0x4b, 0x91, 0x95,
	0xc1, 0x16, 0xb5, 0xac, 0x20, 0xc9, 0xce, 0x5f, 0xe9, 0xbf, 0x2b, 0xf4, 0x97, 0x14, 0x59, 0x76,
	0x21, 0xb9, 0xe4, 0x36, 0xf3, 0x34, 0xf3, 0x66, 0xde, 0xd3, 0xa0, 0x99, 0x06, 0xd5, 0x71, 0x06,
	0xb9, 0x00, 0x43, 0x73, 0x01, 0x5a, 0xd3, 0x12, 0xb2, 0xbd, 0x92, 0x46, 0xe2, 0x54, 0x70, 0x56,
	0xf1, 0xba, 0xcd, 0x0a, 0xc9, 0x6b, 0x50, 0xfb, 0x9a, 0x1a, 0xc8, 0x86, 0xfa, 0xcc, 0xd6, 0xcf,
	0x1e, 0x4a, 0x6e, 0xaa, 0xb6, 0xc8, 0x98, 0x14, 0xb9, 0x38, 0x70, 0xf3, 0x21, 0x0f, 0x79, 0x29,
	0x97, 0x7d, 0xfb, 0xb2, 0xa3, 0x35, 0xdf, 0x51, 0x23, 0x95, 0xce, 0x7f, 0x43, 0xc7, 0x3c, 0xff,
	0xf4, 0x51, 0xb8, 0x06, 0x43, 0xf1, 0x0c, 0x85, 0x0d, 0x15, 0x90, 0x78, 0xa9, 0xb7, 0xf8, 0xb3,
	0x8a, 0xbe, 0xbf, 0xae, 0xfc, 0x57, 0x8f, 0xf4, 0x18, 0xbe, 0x44, 0x91, 0x06, 0xd1, 0x81, 0x4a,
	0xfc, 0xa3, 0xd7, 0x01, 0xc5, 0x29, 0x8a, 0x59, 0x45, 0x9b, 0x06, 0xea, 0x24, 0x38, 0x2a, 0x18,
	0x61, 0xfc, 0x82, 0x62, 0xd5, 0x36, 0x86, 0x0b, 0x48, 0xc2, 0xd4, 0x5b, 0xfc, 0xbd, 0xbb, 0xcd,
	0xce, 0x49, 0xca, 0x88, 0x6b, 0x70, 0x64, 0xa9, 0x47, 0x46, 0x06, 0x3c, 0xb5, 0xeb, 0x28, 0x4e,
	0xeb, 0x64, 0x62, 0xa7, 0x91, 0x21, 0xc3, 0x17, 0x68, 0x52, 0xb4, 0xbc, 0xde, 0x25, 0x51, 0x0f,
	0xbb, 0x04, 0x3f, 0xa2, 0xa0, 0x63, 0x3a, 0x89, 0xfb, 0xb1, 0x37, 0xe7, 0xc7, 0x6e, 0x99, 0x26,
	0xb6, 0x63, 0xfe, 0x8e, 0xe2, 0x61, 0x05, 0x2b, 0xb0, 0x03, 0xa5, 0xb9, 0x6c, 0x4e, 0xfc, 0x19,
	0x61, 0x6b, 0x1f, 0x55, 0xac, 0x3a, 0x31, 0xa8, 0xc7, 0xf0, 0x14, 0xf9, 0x52, 0x9f, 0x38, 0xe3,
	0x4b, 0x3d, 0x7f, 0x46, 0xc1, 0x96, 0x69, 0x8c, 0x51, 0x58, 0x51, 0x5d, 0x39, 0x66, 0xd2, 0xc7,
	0x56, 0x62, 0xa1, 0x68, 0x33, 0x12, 0x92, 0x21, 0xc3, 0xff, 0x51, 0x60, 0x68, 0xe9, 0xb8, 0x88,
	0x0d, 0x57, 0x4f, 0xe8, 0x9a, 0x49, 0x71, 0x56, 0xd6, 0xea, 0xdf, 0xda, 0x5d, 0xd4, 0xc6, 0x7e,
	0xfb, 0xc6, 0x7b, 0x0b, 0x2d, 0x5a, 0x44, 0xfd, 0x15, 0xdc, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x71, 0x8b, 0xd2, 0x26, 0x7d, 0x02, 0x00, 0x00,
}
