// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: message.proto

package meta

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _message_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Meta with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Meta) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		return MetaValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetSemver()) < 1 {
		return MetaValidationError{
			field:  "Semver",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetChannel()) < 1 {
		return MetaValidationError{
			field:  "Channel",
			reason: "value length must be at least 1 runes",
		}
	}

	if m.GetRuntime() == nil {
		return MetaValidationError{
			field:  "Runtime",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetRuntime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MetaValidationError{
				field:  "Runtime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Serial

	// no validation rules for Build

	if v, ok := interface{}(m.GetVcs()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MetaValidationError{
				field:  "Vcs",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// MetaValidationError is the validation error returned by Meta.Validate if the
// designated constraints aren't met.
type MetaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MetaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MetaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MetaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MetaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MetaValidationError) ErrorName() string { return "MetaValidationError" }

// Error satisfies the builtin error interface
func (e MetaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMeta.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MetaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MetaValidationError{}

// Validate checks the field values on Runtime with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Runtime) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetVersion()) < 1 {
		return RuntimeValidationError{
			field:  "Version",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetArch()) < 1 {
		return RuntimeValidationError{
			field:  "Arch",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetOs()) < 1 {
		return RuntimeValidationError{
			field:  "Os",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// RuntimeValidationError is the validation error returned by Runtime.Validate
// if the designated constraints aren't met.
type RuntimeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RuntimeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RuntimeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RuntimeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RuntimeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RuntimeValidationError) ErrorName() string { return "RuntimeValidationError" }

// Error satisfies the builtin error interface
func (e RuntimeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRuntime.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RuntimeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RuntimeValidationError{}

// Validate checks the field values on Vcs with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *Vcs) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Hash

	// no validation rules for Branch

	// no validation rules for Tag

	return nil
}

// VcsValidationError is the validation error returned by Vcs.Validate if the
// designated constraints aren't met.
type VcsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VcsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VcsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VcsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VcsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VcsValidationError) ErrorName() string { return "VcsValidationError" }

// Error satisfies the builtin error interface
func (e VcsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVcs.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VcsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VcsValidationError{}
