// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package echo

import (
	"context"

	"github.com/michilu/boilerplate/v/errs"
	"google.golang.org/grpc/codes"
)

// GetPipeString returns new input(chan<- String)/output(<-chan String) channels that embedded the given 'func(String) String'.
func GetPipeString(
	ctx context.Context,
	fn func(string) (string, error),
	fnErr func(error) bool,
) (
	chan<- string,
	<-chan string,
) {
	const op = "pipe.getPipeString"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if fn == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fn' is nil"})
	}
	if fnErr == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fnErr' is nil"})
	}

	inCh := make(chan string)
	outCh := make(chan string)

	go func() {
		const op = "pipe.getPipeString#go"
		defer close(outCh)
		for i := range inCh {
			o, err := fn(i)
			if err != nil {
				if fnErr(&errs.Error{Op: op, Err: err}) {
					return
				}
				continue
			}
			select {
			case <-ctx.Done():
				err := ctx.Err()
				if err != nil {
					fnErr(&errs.Error{Op: op, Err: err})
				}
				return
			case outCh <- o:
			default:
			}
		}
	}()

	return inCh, outCh
}
