// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package echo

import (
	"context"
	"sync"

	"github.com/michilu/boilerplate/v/errs"
	"google.golang.org/grpc/codes"
)

var (
	topicString *mapString
)

func init() {
	topicString = newMapString()
}

// GetTopicString returns a TopicString of the given topic.
func GetTopicString(topic interface{}) TopicString {
	return topicString.get(topic)
}

// TopicString is a topic.
type TopicString interface {
	// Publish returns a '<-chan String' that joins to the given topic.
	Publish(ctx context.Context, c <-chan string)
	// Publisher returns a 'chan<- String' that joins to the given topic.
	Publisher(ctx context.Context) chan<- string
	// Subscribe returns a 'chan<- String' that joins to the given topic.
	Subscribe(c chan<- string)
}

type tString struct {
	mu sync.RWMutex
	c  []chan<- string
}

func newTString() *tString {
	return &tString{
		c: make([]chan<- string, 0),
	}
}

func (t *tString) Publish(ctx context.Context, c <-chan string) {
	const op = "topic.tString.publish"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if c == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'c' is nil"})
	}

	go func() {
	loop:
		select {
		case <-ctx.Done():
			return
		default:
		}
		for v := range c {
			for _, c := range t.c {
				go func(c chan<- string, v string) {
					select {
					case <-ctx.Done():
						return
					case c <- v:
					}
				}(c, v)
			}
			goto loop
		}
	}()

}

func (t *tString) Publisher(ctx context.Context) chan<- string {
	const op = "topic.tString.publisher"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}

	c := make(chan string)
	t.Publish(ctx, c)
	return c
}

func (t *tString) Subscribe(c chan<- string) {
	const op = "topic.tString.subscribe"

	if c == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'c' is nil"})
	}

	t.mu.Lock()
	t.c = append(t.c, c)
	t.mu.Unlock()
}

type mapString struct {
	mu sync.RWMutex
	m  map[interface{}]*tString
}

func newMapString() *mapString {
	return &mapString{
		m: make(map[interface{}]*tString),
	}
}

func (m *mapString) get(topic interface{}) TopicString {
	const op = "topic.mapString.get"

	if topic == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'topic' is nil"})
	}

	m.mu.RLock()
	v, ok := m.m[topic]
	m.mu.RUnlock()
	if ok {
		return v
	}

	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok = m.m[topic]
	if ok {
		return v
	}
	v = newTString()
	m.m[topic] = v
	return v
}
