// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package event

import (
	"context"
	"fmt"

	"github.com/michilu/boilerplate/service/errs"
	"github.com/michilu/boilerplate/service/slog"
	"github.com/rs/zerolog"
	"google.golang.org/grpc/codes"
)

// EventWithContext is Event with context.Context.
type EventWithContext struct {
	Context context.Context
	Event   Eventer
}

// GetContext returns context.Context.
func (p *EventWithContext) GetContext() context.Context {
	return p.Context
}

// GetEvent returns Eventer.
func (p *EventWithContext) GetEvent() Eventer {
	return p.Event
}

// MarshalZerologObject writes EventWithContext to given zerolog.Event.
func (p *EventWithContext) MarshalZerologObject(e *zerolog.Event) {
	const op = op + ".EventWithContext.MarshalZerologObject"
	if p.Event == nil {
		return
	}
	v, ok := p.Event.(zerolog.LogObjectMarshaler)
	if !ok {
		err := &errs.Error{Op: op, Code: codes.InvalidArgument,
			Message: "'*EventWithContext.Event' must be zerolog.LogObjectMarshaler'"}
		slog.Logger().Error().Str("op", op).Err(err).Msg(err.Error())
		return
	}
	e.Object("EventWithContext", v)
}

// String returns EventWithContext as string.
func (p *EventWithContext) String() string {
	const v0 = "EventWithContext<Context: %v, Event: %v>"
	if p.Event == nil {
		return fmt.Sprintf(v0, p.Context, p.Event)
	}
	v1, ok := p.Event.(fmt.Stringer)
	if !ok {
		return fmt.Sprintf(v0, p.Context, p.Event)
	}
	return fmt.Sprintf(v0, p.Context, v1.String())
}

// Validate returns error if failed validate.
func (p *EventWithContext) Validate() error {
	const op = op + ".EventWithContext.Validate"
	if p.Context == nil {
		err := &errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. '*EventWithContext.Context' is nil"}
		return err
	}
	if p.Event == nil {
		err := &errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. '*EventWithContext.Event' is nil"}
		return err
	}
	v0, ok := p.Event.(interface{ Validate() error })
	if !ok {
		err := &errs.Error{Op: op, Code: codes.InvalidArgument, Message: "'*EventWithContext.Event' must be have 'Validate() error'"}
		return err
	}
	{
		err := v0.Validate()
		if err != nil {
			err := &errs.Error{Op: op, Code: codes.InvalidArgument, Err: err}
			return err
		}
	}
	return nil
}
