// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package event

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Event) Validate() error {
	if !(len(this.Id) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Id))
	}
	if len(this.TimePoint) < 1 {
		return github_com_mwitkow_go_proto_validators.FieldError("TimePoint", fmt.Errorf(`value '%v' must contain at least 1 elements`, this.TimePoint))
	}
	for _, item := range this.TimePoint {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("TimePoint", err)
			}
		}
	}
	return nil
}
func (this *TimePoint) Validate() error {
	if this.Timestamp != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Timestamp); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Timestamp", err)
		}
	}
	if this.Tag == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Tag", fmt.Errorf(`value '%v' must not be an empty string`, this.Tag))
	}
	return nil
}
