// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: appengine.proto

package slog

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _appengine_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on AppengineEntry with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *AppengineEntry) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Time

	// no validation rules for Trace

	if v, ok := interface{}(m.GetSourceLocation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AppengineEntryValidationError{
				field:  "SourceLocation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Severity

	// no validation rules for Message

	// no validation rules for Data

	return nil
}

// AppengineEntryValidationError is the validation error returned by
// AppengineEntry.Validate if the designated constraints aren't met.
type AppengineEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AppengineEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AppengineEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AppengineEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AppengineEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AppengineEntryValidationError) ErrorName() string { return "AppengineEntryValidationError" }

// Error satisfies the builtin error interface
func (e AppengineEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAppengineEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AppengineEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AppengineEntryValidationError{}

// Validate checks the field values on AppengineSourceLocation with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *AppengineSourceLocation) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for File

	// no validation rules for Line

	// no validation rules for Function

	return nil
}

// AppengineSourceLocationValidationError is the validation error returned by
// AppengineSourceLocation.Validate if the designated constraints aren't met.
type AppengineSourceLocationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AppengineSourceLocationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AppengineSourceLocationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AppengineSourceLocationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AppengineSourceLocationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AppengineSourceLocationValidationError) ErrorName() string {
	return "AppengineSourceLocationValidationError"
}

// Error satisfies the builtin error interface
func (e AppengineSourceLocationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAppengineSourceLocation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AppengineSourceLocationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AppengineSourceLocationValidationError{}
