// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/slog/appengine.proto

package slog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AppengineEntry is ValueObject.
type AppengineEntry struct {
	Time                 string              `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Trace                string              `protobuf:"bytes,2,opt,name=trace,proto3" json:"logging.googleapis.com/trace,omitempty"`
	SourceLocation       *SourceLocation     `protobuf:"bytes,3,opt,name=source_location,json=sourceLocation,proto3" json:"logging.googleapis.com/sourceLocation,omitempty"`
	Severity             string              `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Message              string              `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Data                 map[string]*any.Any `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AppengineEntry) Reset()         { *m = AppengineEntry{} }
func (m *AppengineEntry) String() string { return proto.CompactTextString(m) }
func (*AppengineEntry) ProtoMessage()    {}
func (*AppengineEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e181ce6b77c4050e, []int{0}
}

func (m *AppengineEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppengineEntry.Unmarshal(m, b)
}
func (m *AppengineEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppengineEntry.Marshal(b, m, deterministic)
}
func (m *AppengineEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppengineEntry.Merge(m, src)
}
func (m *AppengineEntry) XXX_Size() int {
	return xxx_messageInfo_AppengineEntry.Size(m)
}
func (m *AppengineEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AppengineEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AppengineEntry proto.InternalMessageInfo

func (m *AppengineEntry) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *AppengineEntry) GetTrace() string {
	if m != nil {
		return m.Trace
	}
	return ""
}

func (m *AppengineEntry) GetSourceLocation() *SourceLocation {
	if m != nil {
		return m.SourceLocation
	}
	return nil
}

func (m *AppengineEntry) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

func (m *AppengineEntry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AppengineEntry) GetData() map[string]*any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// SourceLocation is ValueObject.
type SourceLocation struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Line                 string   `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Function             string   `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceLocation) Reset()         { *m = SourceLocation{} }
func (m *SourceLocation) String() string { return proto.CompactTextString(m) }
func (*SourceLocation) ProtoMessage()    {}
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e181ce6b77c4050e, []int{1}
}

func (m *SourceLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceLocation.Unmarshal(m, b)
}
func (m *SourceLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceLocation.Marshal(b, m, deterministic)
}
func (m *SourceLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceLocation.Merge(m, src)
}
func (m *SourceLocation) XXX_Size() int {
	return xxx_messageInfo_SourceLocation.Size(m)
}
func (m *SourceLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceLocation.DiscardUnknown(m)
}

var xxx_messageInfo_SourceLocation proto.InternalMessageInfo

func (m *SourceLocation) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *SourceLocation) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *SourceLocation) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func init() {
	proto.RegisterType((*AppengineEntry)(nil), "michilu.boilerplate.service.slog.AppengineEntry")
	proto.RegisterMapType((map[string]*any.Any)(nil), "michilu.boilerplate.service.slog.AppengineEntry.DataEntry")
	proto.RegisterType((*SourceLocation)(nil), "michilu.boilerplate.service.slog.SourceLocation")
}

func init() { proto.RegisterFile("service/slog/appengine.proto", fileDescriptor_e181ce6b77c4050e) }

var fileDescriptor_e181ce6b77c4050e = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0x36, 0x2d, 0xf4, 0x2a, 0x15, 0x64, 0x75, 0x30, 0x15, 0x43, 0xd4, 0xa9, 0x62,
	0x70, 0x50, 0x59, 0x50, 0xb7, 0x22, 0xd8, 0x80, 0x21, 0xb0, 0xc0, 0x82, 0xdc, 0x70, 0x0d, 0x16,
	0xae, 0x1d, 0xd9, 0x4e, 0xa5, 0x7c, 0x65, 0x3e, 0x05, 0xb2, 0xd3, 0x44, 0xea, 0xd4, 0xed, 0xbd,
	0xb3, 0xdf, 0xfd, 0xf9, 0xc1, 0xb5, 0x45, 0xb3, 0x17, 0x39, 0xa6, 0x56, 0xea, 0x22, 0xe5, 0x65,
	0x89, 0xaa, 0x10, 0x0a, 0x59, 0x69, 0xb4, 0xd3, 0x24, 0xd9, 0x89, 0xfc, 0x47, 0xc8, 0x8a, 0x6d,
	0xb4, 0x90, 0x68, 0x4a, 0xc9, 0x1d, 0xb2, 0x43, 0x82, 0xf9, 0xc4, 0xec, 0xaa, 0xd0, 0xba, 0x90,
	0x98, 0x86, 0xff, 0x9b, 0x6a, 0x9b, 0x72, 0x55, 0x37, 0xe1, 0xf9, 0x5f, 0x0f, 0x26, 0xeb, 0xb6,
	0xe1, 0x93, 0x72, 0xa6, 0x26, 0x04, 0x62, 0x27, 0x76, 0x48, 0xa3, 0x24, 0x5a, 0x8c, 0xb2, 0xa0,
	0xc9, 0x14, 0x06, 0xce, 0xf0, 0x1c, 0x69, 0x2f, 0x14, 0x1b, 0x43, 0x3e, 0xe0, 0xc2, 0xea, 0xca,
	0xe4, 0xf8, 0x25, 0x75, 0xce, 0x9d, 0xd0, 0x8a, 0xf6, 0x93, 0x68, 0x31, 0x5e, 0xde, 0xb2, 0x53,
	0x3b, 0xb1, 0xb7, 0x10, 0x7c, 0x3e, 0xe4, 0xb2, 0x89, 0x3d, 0xf2, 0x64, 0x06, 0xe7, 0x16, 0xf7,
	0x68, 0x84, 0xab, 0x69, 0x1c, 0x66, 0x76, 0x9e, 0x50, 0x38, 0xdb, 0xa1, 0xb5, 0xbc, 0x40, 0x3a,
	0x08, 0x4f, 0xad, 0x25, 0xaf, 0x10, 0x7f, 0x73, 0xc7, 0xe9, 0x30, 0xe9, 0x2f, 0xc6, 0xcb, 0xd5,
	0xe9, 0x2d, 0x8e, 0x4f, 0x67, 0x8f, 0xdc, 0xf1, 0xa0, 0xb2, 0xd0, 0x67, 0xf6, 0x02, 0xa3, 0xae,
	0x44, 0x2e, 0xa1, 0xff, 0x8b, 0xf5, 0x01, 0x8b, 0x97, 0xe4, 0x06, 0x06, 0x7b, 0x2e, 0xab, 0x86,
	0xca, 0x78, 0x39, 0x65, 0x0d, 0x67, 0xd6, 0x72, 0x66, 0x6b, 0x55, 0x67, 0xcd, 0x97, 0x55, 0xef,
	0x3e, 0x9a, 0xbf, 0xc3, 0xe4, 0xf8, 0x6c, 0xcf, 0x7a, 0x2b, 0x64, 0xc7, 0xda, 0x6b, 0x5f, 0x93,
	0x42, 0xb5, 0xa8, 0x83, 0xf6, 0x38, 0xb6, 0x95, 0xca, 0x3b, 0xc4, 0xa3, 0xac, 0xf3, 0x0f, 0xc3,
	0xcf, 0xd8, 0xdf, 0xb2, 0x19, 0x86, 0xb1, 0x77, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x7d,
	0xc2, 0x7a, 0x2e, 0x02, 0x00, 0x00,
}
