@startuml

queue debug..ctx[
topic("debug")
--
context.Context
]

queue debug..Clienter[
topic("debug")
--
ClientWithContexter
]

actor cmd.run
cmd.run->debug..ctx
debug..ctx->config
config->debug..Clienter
debug..Clienter->connect
connect->debug..ctx

@enduml