@startuml
left to right direction

usecase uc1 <<use case>>[
uc-debug.1
generate UUID
]

usecase uc2 <<use case>>[
uc-debug.2
open debug port
]

:client:--(uc1)
:client:--(uc2)
(uc1)--:system:
(uc2)--:system:

@enduml
