# https://cloud.google.com/appengine/docs/standard/go/config/appref

runtime: go113
inbound_services:
- warmup
includes:
- secret.yaml
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 0
  min_idle_instances: 0
