// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package now

import (
	"context"
	"sync"

	"github.com/michilu/boilerplate/service/errs"
	"github.com/michilu/boilerplate/service/slog"
	"google.golang.org/grpc/codes"
)

var (
	topicContextContext *mapContextContext
)

func init() {
	topicContextContext = newMapContextContext()
}

// GetTopicContextContext returns a TopicContextContext of the given topic.
func GetTopicContextContext(topic interface{}) TopicContextContext {
	return topicContextContext.get(topic)
}

// TopicContextContext is a topic.
type TopicContextContext interface {
	// Publish returns a '<-chan ContextContext' that joins to the given topic.
	Publish(ctx context.Context, c <-chan context.Context)
	// Publisher returns a 'chan<- ContextContext' that joins to the given topic.
	Publisher(ctx context.Context) chan<- context.Context
	// Subscribe returns a 'chan<- ContextContext' that joins to the given topic.
	Subscribe(c chan<- context.Context)
}

type tContextContext struct {
	mu sync.RWMutex
	c  []chan<- context.Context
}

func newTContextContext() *tContextContext {
	return &tContextContext{
		c: make([]chan<- context.Context, 0),
	}
}

func (t *tContextContext) Publish(ctx context.Context, c <-chan context.Context) {
	const op = op + ".tContextContext.Publish"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if c == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'c' is nil"})
	}

	go slog.Recover(ctx, func(ctx context.Context) error {
		const op = op + "#go"
	loop:
		select {
		case <-ctx.Done():
			if err := ctx.Err(); err != nil {
				return &errs.Error{Op: op, Err: err}
			}
			return nil
		default:
		}
		for v := range c {
			for _, c := range t.c {
				go slog.Recover(ctx, func(ctx context.Context) error {
					func(c chan<- context.Context, v context.Context) {
						const op = op + "#func"
						select {
						case <-ctx.Done():
							err := &errs.Error{Op: op, Code: codes.Canceled, Err: ctx.Err()}
							slog.Logger().Debug().Err(err).Str("op", op).Msg(err.Error())
							return
						case c <- v:
						}
					}(c, v)
					return nil
				})
			}
			goto loop
		}
		return nil
	})

}

func (t *tContextContext) Publisher(ctx context.Context) chan<- context.Context {
	const op = op + ".tContextContext.Publisher"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}

	c := make(chan context.Context)
	t.Publish(ctx, c)
	return c
}

func (t *tContextContext) Subscribe(c chan<- context.Context) {
	const op = op + ".tContextContext.Subscribe"

	if c == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'c' is nil"})
	}

	t.mu.Lock()
	t.c = append(t.c, c)
	t.mu.Unlock()
}

type mapContextContext struct {
	mu sync.RWMutex
	m  map[interface{}]*tContextContext
}

func newMapContextContext() *mapContextContext {
	return &mapContextContext{
		m: make(map[interface{}]*tContextContext),
	}
}

func (m *mapContextContext) get(topic interface{}) TopicContextContext {
	const op = op + ".mapContextContext.get"

	if topic == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'topic' is nil"})
	}

	m.mu.RLock()
	v, ok := m.m[topic]
	m.mu.RUnlock()
	if ok {
		return v
	}

	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok = m.m[topic]
	if ok {
		return v
	}
	v = newTContextContext()
	m.m[topic] = v
	return v
}
