// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package now

import (
	"context"
	"sync"
	"time"

	"github.com/michilu/boilerplate/service/errs"
	"google.golang.org/grpc/codes"
)

var (
	topicTimeTime *mapTimeTime
)

func init() {
	topicTimeTime = newMapTimeTime()
}

// GetTopicTimeTime returns a TopicTimeTime of the given topic.
func GetTopicTimeTime(topic interface{}) TopicTimeTime {
	return topicTimeTime.get(topic)
}

// TopicTimeTime is a topic.
type TopicTimeTime interface {
	// Publish returns a '<-chan TimeTime' that joins to the given topic.
	Publish(ctx context.Context, c <-chan time.Time)
	// Publisher returns a 'chan<- TimeTime' that joins to the given topic.
	Publisher(ctx context.Context) chan<- time.Time
	// Subscribe returns a 'chan<- TimeTime' that joins to the given topic.
	Subscribe(c chan<- time.Time)
}

type tTimeTime struct {
	mu sync.RWMutex
	c  []chan<- time.Time
}

func newTTimeTime() *tTimeTime {
	return &tTimeTime{
		c: make([]chan<- time.Time, 0),
	}
}

func (t *tTimeTime) Publish(ctx context.Context, c <-chan time.Time) {
	const op = op + ".tTimeTime.Publish"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if c == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'c' is nil"})
	}

	go func() {
	loop:
		select {
		case <-ctx.Done():
			return
		default:
		}
		for v := range c {
			for _, c := range t.c {
				go func(c chan<- time.Time, v time.Time) {
					select {
					case <-ctx.Done():
						return
					case c <- v:
					}
				}(c, v)
			}
			goto loop
		}
	}()

}

func (t *tTimeTime) Publisher(ctx context.Context) chan<- time.Time {
	const op = op + ".tTimeTime.Publisher"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}

	c := make(chan time.Time)
	t.Publish(ctx, c)
	return c
}

func (t *tTimeTime) Subscribe(c chan<- time.Time) {
	const op = op + ".tTimeTime.Subscribe"

	if c == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'c' is nil"})
	}

	t.mu.Lock()
	t.c = append(t.c, c)
	t.mu.Unlock()
}

type mapTimeTime struct {
	mu sync.RWMutex
	m  map[interface{}]*tTimeTime
}

func newMapTimeTime() *mapTimeTime {
	return &mapTimeTime{
		m: make(map[interface{}]*tTimeTime),
	}
}

func (m *mapTimeTime) get(topic interface{}) TopicTimeTime {
	const op = op + ".mapTimeTime.get"

	if topic == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'topic' is nil"})
	}

	m.mu.RLock()
	v, ok := m.m[topic]
	m.mu.RUnlock()
	if ok {
		return v
	}

	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok = m.m[topic]
	if ok {
		return v
	}
	v = newTTimeTime()
	m.m[topic] = v
	return v
}
