// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package terminate

import (
	"context"

	"github.com/michilu/boilerplate/service/errs"
	"google.golang.org/grpc/codes"
)

// GetPipeStruct returns new input(chan<- Struct)/output(<-chan Struct) channels that embedded the given 'func(Struct) Struct'.
func GetPipeStruct(
	ctx context.Context,
	fn func(struct{}) (struct{}, error),
	fnErr func(error) bool,
) (
	chan<- struct{},
	<-chan struct{},
) {
	const op = op + ".GetPipeStruct"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if fn == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fn' is nil"})
	}
	if fnErr == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fnErr' is nil"})
	}

	inCh := make(chan struct{})
	outCh := make(chan struct{})

	go func() {
		const op = op + "#go"
		defer close(outCh)
		for i := range inCh {
			o, err := fn(i)
			if err != nil {
				if fnErr(&errs.Error{Op: op, Err: err}) {
					return
				}
				continue
			}
			select {
			case <-ctx.Done():
				err := ctx.Err()
				if err != nil {
					fnErr(&errs.Error{Op: op, Err: err})
				}
				return
			case outCh <- o:
			default:
			}
		}
	}()

	return inCh, outCh
}

// GetFanoutStruct returns new input(chan<- Struct)/output(<-chan Struct) channels that embedded the given 'func(Struct) Struct'.
func GetFanoutStruct(
	ctx context.Context,
	fn func(struct{}) ([]struct{}, error),
	fnErr func(error) bool,
) (
	chan<- struct{},
	<-chan struct{},
) {
	const op = op + ".GetFanoutStruct"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if fn == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fn' is nil"})
	}
	if fnErr == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'fnErr' is nil"})
	}

	inCh := make(chan struct{})
	outCh := make(chan struct{})

	go func() {
		const op = op + "#go"
		defer close(outCh)
		for i := range inCh {
			o, err := fn(i)
			if err != nil {
				if fnErr(&errs.Error{Op: op, Err: err}) {
					return
				}
				continue
			}
			for _, v := range o {
				select {
				case <-ctx.Done():
					err := ctx.Err()
					if err != nil {
						fnErr(&errs.Error{Op: op, Err: err})
					}
					return
				case outCh <- v:
				default:
				}
			}
		}
	}()

	return inCh, outCh
}
