// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package terminate

import (
	"context"
	"sync"

	"github.com/michilu/boilerplate/service/errs"
	"google.golang.org/grpc/codes"
)

var (
	topicStruct *mapStruct
)

func init() {
	topicStruct = newMapStruct()
}

// GetTopicStruct returns a TopicStruct of the given topic.
func GetTopicStruct(topic interface{}) TopicStruct {
	return topicStruct.get(topic)
}

// TopicStruct is a topic.
type TopicStruct interface {
	// Publish returns a '<-chan Struct' that joins to the given topic.
	Publish(ctx context.Context, c <-chan struct{})
	// Publisher returns a 'chan<- Struct' that joins to the given topic.
	Publisher(ctx context.Context) chan<- struct{}
	// Subscribe returns a 'chan<- Struct' that joins to the given topic.
	Subscribe(c chan<- struct{})
}

type tStruct struct {
	mu sync.RWMutex
	c  []chan<- struct{}
}

func newTStruct() *tStruct {
	return &tStruct{
		c: make([]chan<- struct{}, 0),
	}
}

func (t *tStruct) Publish(ctx context.Context, c <-chan struct{}) {
	const op = op + ".tStruct.Publish"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}
	if c == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'c' is nil"})
	}

	go func() {
	loop:
		select {
		case <-ctx.Done():
			return
		default:
		}
		for v := range c {
			for _, c := range t.c {
				go func(c chan<- struct{}, v struct{}) {
					select {
					case <-ctx.Done():
						return
					case c <- v:
					}
				}(c, v)
			}
			goto loop
		}
	}()

}

func (t *tStruct) Publisher(ctx context.Context) chan<- struct{} {
	const op = op + ".tStruct.Publisher"

	if ctx == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'ctx' is nil"})
	}

	c := make(chan struct{})
	t.Publish(ctx, c)
	return c
}

func (t *tStruct) Subscribe(c chan<- struct{}) {
	const op = op + ".tStruct.Subscribe"

	if c == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'c' is nil"})
	}

	t.mu.Lock()
	t.c = append(t.c, c)
	t.mu.Unlock()
}

type mapStruct struct {
	mu sync.RWMutex
	m  map[interface{}]*tStruct
}

func newMapStruct() *mapStruct {
	return &mapStruct{
		m: make(map[interface{}]*tStruct),
	}
}

func (m *mapStruct) get(topic interface{}) TopicStruct {
	const op = op + ".mapStruct.get"

	if topic == nil {
		panic(&errs.Error{Op: op, Code: codes.InvalidArgument, Message: "must be given. 'topic' is nil"})
	}

	m.mu.RLock()
	v, ok := m.m[topic]
	m.mu.RUnlock()
	if ok {
		return v
	}

	m.mu.Lock()
	defer m.mu.Unlock()
	v, ok = m.m[topic]
	if ok {
		return v
	}
	v = newTStruct()
	m.m[topic] = v
	return v
}
