// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/client/message.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Client is Entity of client infomation
type Client struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Debug                *Debug   `protobuf:"bytes,2,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_651aa032c2fcbfcd, []int{0}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Client) GetDebug() *Debug {
	if m != nil {
		return m.Debug
	}
	return nil
}

// Debug is Entity
type Debug struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Debug) Reset()         { *m = Debug{} }
func (m *Debug) String() string { return proto.CompactTextString(m) }
func (*Debug) ProtoMessage()    {}
func (*Debug) Descriptor() ([]byte, []int) {
	return fileDescriptor_651aa032c2fcbfcd, []int{1}
}

func (m *Debug) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Debug.Unmarshal(m, b)
}
func (m *Debug) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Debug.Marshal(b, m, deterministic)
}
func (m *Debug) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Debug.Merge(m, src)
}
func (m *Debug) XXX_Size() int {
	return xxx_messageInfo_Debug.Size(m)
}
func (m *Debug) XXX_DiscardUnknown() {
	xxx_messageInfo_Debug.DiscardUnknown(m)
}

var xxx_messageInfo_Debug proto.InternalMessageInfo

func (m *Debug) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*Client)(nil), "michilu.boilerplate.service.client.Client")
	proto.RegisterType((*Debug)(nil), "michilu.boilerplate.service.client.Debug")
}

func init() { proto.RegisterFile("service/client/message.proto", fileDescriptor_651aa032c2fcbfcd) }

var fileDescriptor_651aa032c2fcbfcd = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0xca, 0xcd, 0x4c, 0xce, 0xc8, 0xcc,
	0x29, 0xd5, 0x4b, 0xca, 0xcf, 0xcc, 0x49, 0x2d, 0x2a, 0xc8, 0x49, 0x2c, 0x49, 0xd5, 0x83, 0xea,
	0xd0, 0x83, 0xe8, 0x90, 0x32, 0x4b, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5,
	0xcf, 0x2d, 0xcf, 0x2c, 0xc9, 0xce, 0x2f, 0xd7, 0x4f, 0xcf, 0xd7, 0x05, 0x1b, 0xa0, 0x5b, 0x96,
	0x98, 0x93, 0x99, 0x92, 0x58, 0x92, 0x5f, 0x54, 0xac, 0x0f, 0x67, 0x42, 0xcc, 0x56, 0x4a, 0xe1,
	0x62, 0x73, 0x06, 0x9b, 0x20, 0x24, 0xc9, 0xc5, 0x94, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0xe9, 0xc4, 0xf9, 0xe8, 0xbe, 0x3c, 0x6b, 0x04, 0xe3, 0x04, 0x46, 0x96, 0x20, 0xa6, 0xcc, 0x14,
	0x21, 0x7b, 0x2e, 0xd6, 0x94, 0xd4, 0xa4, 0xd2, 0x74, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23,
	0x4d, 0x3d, 0xc2, 0x0e, 0xd2, 0x73, 0x01, 0x69, 0x08, 0x82, 0xe8, 0x53, 0x52, 0xe5, 0x62, 0x05,
	0xf3, 0x85, 0x64, 0xb8, 0x58, 0x0a, 0xf2, 0x8b, 0x4a, 0xc0, 0xd6, 0xf0, 0x3a, 0x71, 0x3c, 0xba,
	0x2f, 0xcf, 0x22, 0xd1, 0xd0, 0xc0, 0x12, 0x04, 0x16, 0x75, 0x72, 0xe0, 0x52, 0x4b, 0xce, 0xcf,
	0x25, 0xc2, 0x74, 0x27, 0x1e, 0x5f, 0x48, 0x08, 0x05, 0x80, 0x3c, 0x11, 0xc0, 0x18, 0xc5, 0x06,
	0x11, 0x4f, 0x62, 0x03, 0xfb, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xad, 0x91, 0x30, 0x21,
	0x51, 0x01, 0x00, 0x00,
}
