// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/keyvalue.proto

package pb

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Key is Entity.
type Key struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_c84630d7b6b89de1, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// KeyValue is Entity.
type KeyValue struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c84630d7b6b89de1, []int{1}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// KeyPrefix is ValueObject.
type KeyPrefix struct {
	Prefix               []byte   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPrefix) Reset()         { *m = KeyPrefix{} }
func (m *KeyPrefix) String() string { return proto.CompactTextString(m) }
func (*KeyPrefix) ProtoMessage()    {}
func (*KeyPrefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_c84630d7b6b89de1, []int{2}
}

func (m *KeyPrefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPrefix.Unmarshal(m, b)
}
func (m *KeyPrefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPrefix.Marshal(b, m, deterministic)
}
func (m *KeyPrefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPrefix.Merge(m, src)
}
func (m *KeyPrefix) XXX_Size() int {
	return xxx_messageInfo_KeyPrefix.Size(m)
}
func (m *KeyPrefix) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPrefix.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPrefix proto.InternalMessageInfo

func (m *KeyPrefix) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func init() {
	proto.RegisterType((*Key)(nil), "michilu.boilerplate.pb.Key")
	proto.RegisterType((*KeyValue)(nil), "michilu.boilerplate.pb.KeyValue")
	proto.RegisterType((*KeyPrefix)(nil), "michilu.boilerplate.pb.KeyPrefix")
}

func init() { proto.RegisterFile("pb/keyvalue.proto", fileDescriptor_c84630d7b6b89de1) }

var fileDescriptor_c84630d7b6b89de1 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x48, 0xd2, 0xcf,
	0x4e, 0xad, 0x2c, 0x4b, 0xcc, 0x29, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcb,
	0xcd, 0x4c, 0xce, 0xc8, 0xcc, 0x29, 0xd5, 0x4b, 0xca, 0xcf, 0xcc, 0x49, 0x2d, 0x2a, 0xc8, 0x49,
	0x2c, 0x49, 0xd5, 0x2b, 0x48, 0x92, 0x72, 0x4c, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce,
	0xcf, 0xd5, 0x4f, 0xcd, 0x2b, 0xcb, 0xaf, 0x2c, 0x28, 0xca, 0xaf, 0xa8, 0xd4, 0x07, 0x6b, 0x4a,
	0xd6, 0x4d, 0x4f, 0xcd, 0xd3, 0x2d, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0x49, 0xd5, 0xc7, 0x60,
	0x40, 0x8c, 0x56, 0x52, 0xe0, 0x62, 0xf6, 0x4e, 0xad, 0x14, 0x92, 0xe4, 0x62, 0xce, 0x4e, 0xad,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x71, 0x62, 0xff, 0xe5, 0xc4, 0x52, 0xc5, 0x24, 0xc0, 0x18,
	0x04, 0x12, 0x53, 0x72, 0xe1, 0xe2, 0xf0, 0x4e, 0xad, 0x0c, 0x03, 0x39, 0x07, 0x8f, 0x32, 0x21,
	0x59, 0x2e, 0x56, 0xb0, 0x93, 0x25, 0x98, 0x50, 0x25, 0x21, 0xa2, 0x4a, 0x3a, 0x5c, 0x9c, 0xde,
	0xa9, 0x95, 0x01, 0x45, 0xa9, 0x69, 0x99, 0x15, 0x42, 0xf2, 0x5c, 0x6c, 0x05, 0x60, 0x16, 0xba,
	0x49, 0x50, 0x61, 0x27, 0x96, 0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0x13, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x36, 0x42, 0xff, 0xb7, 0x12, 0x01, 0x00, 0x00,
}
